# Generated by Django 3.1 on 2020-08-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_auto_20200827_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('title', models.SlugField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='HashTag',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='insta.Tag'),
        ),
    ]
